### ISSUE TITLE
pip install pip install django-absolute==0.2 fails

### ISSUE THREAD

**Issue by piotrkilczuk** [noirbizarre/django-absolute#2]
Thanks for fixing #1, nice one, but...

```
(_env)[piotr@piotr-amd tmp]$ pip install django-absolute==0.2
Downloading/unpacking django-absolute==0.2
  Running setup.py egg_info for package django-absolute
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/piotr/tmp/_env/build/django-absolute/setup.py", line 19, in <module>
    rst('CHANGELOG.rst'),
      File "/home/piotr/tmp/_env/build/django-absolute/setup.py", line 13, in rst
    content = open(filename).read()
    IOError: [Errno 2] No such file or directory: 'CHANGELOG.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/piotr/tmp/_env/build/django-absolute/setup.py", line 19, in <module>

    rst('CHANGELOG.rst'),

  File "/home/piotr/tmp/_env/build/django-absolute/setup.py", line 13, in rst

    content = open(filename).read()

IOError: [Errno 2] No such file or directory: 'CHANGELOG.rst'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/piotr/tmp/_env/build/django-absolute
Storing complete log in /home/piotr/.pip/pip.log
```

`pip install -e ...` for 0.3dev is fine

**Comment by noirbizarre** [comment]
This issue is fixed by dcb00881fca859e9a841e649e7dc02902aeb44b6
Version 0.2.1 has been released including this fix, so:

``` bash
pip install django-absolute>=0.2.1
```

should be fine.
I will remove release 0.2 from pypi to ensure nobody will try to install it anymore.

By the way, you're welcome for #1.
